Repository nonebot/adapter-onebot, pull requests merged in 2024-02, with the labels that each got.

#88 Fix: `get_forward_msg` 接口返回类型注释错误
  nonebot/adapters/onebot/v11/bot.pyi
Labels: bug

#91 Fix: 回复消息的 id 应该为 int 类型
  nonebot/adapters/onebot/v11/bot.py
Labels: bug, v11

#90 Feature: 支持 Pydantic v2
  nonebot/adapters/onebot/collator.py
  nonebot/adapters/onebot/compat.py
  nonebot/adapters/onebot/utils.py
  nonebot/adapters/onebot/v11/adapter.py
  nonebot/adapters/onebot/v11/bot.py
  nonebot/adapters/onebot/v11/config.py
  nonebot/adapters/onebot/v11/event.py
  nonebot/adapters/onebot/v12/adapter.py
  nonebot/adapters/onebot/v12/bot.py
  nonebot/adapters/onebot/v12/config.py
  nonebot/adapters/onebot/v12/event.py
  nonebot/adapters/onebot/v12/utils.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_collator.py
  tests/test_store.py
  tests/v11/test_v11_connection.py
  tests/v11/test_v11_event.py
  tests/v11/test_v11_message.py
  tests/v12/test_v12_api.py
  tests/v12/test_v12_connection.py
  tests/v12/test_v12_event.py
  tests/v12/test_v12_message.py
Labels: enhancement

#93 Fix: pydantic v2 `URL` support
  nonebot/adapters/onebot/v11/adapter.py
  nonebot/adapters/onebot/v12/adapter.py
Labels: bug

#96 Fix: 配置项无法使用字段名填写
  nonebot/adapters/onebot/v11/config.py
  nonebot/adapters/onebot/v12/config.py
  tests/conftest.py
  tests/v11/test_v11_config.py
  tests/v11/test_v11_connection.py
  tests/v12/test_v12_config.py
  tests/v12/test_v12_connection.py
  website/docs/guide/configuration.md
Labels: bug

#97 Fix: 消息段数据采用 str 存储
  nonebot/adapters/onebot/v11/message.py
Labels: bug
